### PR TITLE
Fixing Clang errors to compile with clang-17

### LINKED ISSUE #622: [BUG] Clang cannot compile as a host compiler
Clang-17 shows a lot of warnings when compiling matx

### PR DESCRIPTION
**Pull request by cliffburdick**
Closes #622

### CODE REVIEW

File: include/matx/core/half.h
Comment (tylera-nvidia) [inline include/matx/core/half.h:1]: do we intend to lose these constructors on the device? I noticed there are more files that you changed from `__host__ __device__` to no qualifier, so want to make sure there isn't some assumption built in here, and that we're actually removing use of them on the device.

File: include/matx/generators/random.h [hunk 1]
```diff
@@ -546,6 +552,9 @@ template <typename T, int RANK> class randomTensorView_t {
             curandGenerateNormalDouble(gen_, &tmp[1], 1, beta_, alpha_);
           }
         }
+        else {
+          val = 0;
```
Comment (tylera-nvidia) [inline include/matx/generators/random.h:556]: Do we want to return zero versus throwing an error? I would assume something is broken if I call a random generator and get all zeros.

File: include/matx/generators/random.h [hunk 2]
```diff
@@ -401,6 +401,11 @@ template <typename T, int RANK> class randomTensorView_t {
         using scalar_type = T;
         using matxop = bool;
 
+        static_assert(std::is_same_v<T, float> ||
```
Comment (tylera-nvidia) [inline include/matx/generators/random.h:404]: We should update the documentation for random to reflect it only works for float types. currently we don't have any verbiage to outline that

File: include/matx/generators/random.h (hunk 1 above)
Comment (cliffburdick) [reply include/matx/generators/random.h:556]: This is device code, so we can't really throw an error here

File: include/matx/core/half.h
Comment (cliffburdick) [reply include/matx/core/half.h:1]: it was getting an error in clang, and since we don't use these on the device at the moment I'm going to leave them this way. If we have a need to later we can add it back.

**Review by tylera-nvidia — APPROVED** [review]
