### PR TITLE
Fix ExecArgReduce compile error with matxBinaryOp

### LINKED ISSUE #946: [BUG] argmax compile error with matxBinaryOp
**Describe the Bug**

When matx::argmax() is used with a matxBinaryOp such as matx::abs(), there is a compiler error from iterator.h

```
/build/_deps/matx-src/include/matx/core/iterator.h(357): error: expression must be an lvalue
            auto &tmp = const_cast<const_strip_type&>(t_.operator()(args...));
                                                      ^
          detected during:
            instantiation of function "lambda [](auto &&...)->matx::RandomOperatorThrustIterator<matx::detail::base_type_t<const matx::detail::matxUnaryOp<matx::detail::base_type_t<matx::tensor_t<float, 1, matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float>>>, matx::DefaultDescriptor<1>>>, matx::detail::AbsOp<matx::extract_value_type_t<matx::tensor_t<float, 1, matx::basic_storage<matx::raw_pointer_buffer<float, matx::matx_allocator<float>>>, matx::DefaultDescriptor<1>>>>> &>, true>::reference [with <auto-1>=<matx::index_t &>]" at line 391 of /build/_deps/cccl-src/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/__functional/invoke.h
            instantiation of "decltype((<expression>)) cuda::std::__4::__invoke(_Fp &&, _Args &&...) [with _Fp=lambda [](auto &&...)->float &, _Args=<long long &>]" at line 1362 of /build/_deps/cccl-src/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/detail/libcxx/include/tuple
            instantiation of "decltype(auto) cuda::std::__4::apply(_Fn &&, _Tuple &&) [with _Fn=lambda [](auto &&...)->float &, _Tuple=cuda::std::__4::array<long long, 1UL> &]" at line 359
            instantiation of "matx::RandomOperatorThrustIterator<OperatorType, ConvertType>::reference matx::RandomOperatorThrustIterator<OperatorType, ConvertType>::operator*() const [with OperatorType=matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>>, ConvertType=true]" at line 105 of /build/_deps/cccl-src/lib/cmake/thrust/../../../thrust/thrust/iterator/detail/zip_iterator_base.h
            instantiation of "thrust::detail::dereference_iterator::apply<Iterator>::type thrust::detail::dereference_iterator::operator()(const Iterator &) [with Iterator=matx::RandomOperatorThrustIterator<matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>>, true>]" at line 52 of /build/_deps/cccl-src/lib/cmake/thrust/../../../thrust/thrust/detail/tuple_transform.h
            [ 21 instantiation contexts not shown ]
            instantiation of "void matx::cub_argreduce(OutputTensor &, TensorIndexType &, const InputOperator &, const CParams &, cudaStream_t) [with OutputTensor=matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, TensorIndexType=matx::detail::tensor_impl_t<matx::index_t, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<matx::index_t>>, InputOperator=matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>>, CParams=matx::detail::ReduceParams_t<matx::detail::CustomArgMaxCmp, const cuda::std::__4::tuple<matx::index_t, float>>]" at line 2078 of /build/_deps/matx-src/include/matx/transforms/reduce.h
            instantiation of "void matx::argmax_impl(OutType, TensorIndexType &, const InType &, matx::cudaExecutor) [with OutType=matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, TensorIndexType=matx::detail::tensor_impl_t<matx::index_t, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<matx::index_t>>, InType=matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>>]" at line 69 of /build/_deps/matx-src/include/matx/operators/argmax.h
            instantiation of "void matx::detail::ArgMaxOp<OpA, ORank>::Exec(Out &&, Executor &&) const [with OpA=const matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>> &, ORank=0, Out=cuda::std::__4::tuple<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::tensor_impl_t<matx::index_t, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<matx::index_t>>, matx::detail::ArgMaxOp<const matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>> &, 0>> &, Executor=matx::cudaExecutor &]" at line 100 of /build/_deps/matx-src/include/matx/core/tie.h
            instantiation of "void matx::mtie<Ts...>::Exec(Executor &&) [with Ts=<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::tensor_impl_t<matx::index_t, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<matx::index_t>>, matx::detail::ArgMaxOp<const matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>> &, 0>>, Executor=matx::cudaExecutor &]" at line 73 of /build/_deps/matx-src/include/matx/operators/base_operator.h
            instantiation of "void matx::BaseOp<T>::run(Ex &&) [with T=matx::mtie<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::tensor_impl_t<matx::index_t, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<matx::index_t>>, matx::detail::ArgMaxOp<const matx::detail::matxUnaryOp<matx::detail::tensor_impl_t<float, 1, matx::tensor_desc_t<cuda::std::__4::array<long long, 1UL>, cuda::std::__4::array<long long, 1UL>, 1>, matx::detail::DenseTensorData<float>>, matx::detail::UnOp<float, matx::detail::AbsF<float>>> &, 0>>, Ex=matx::cudaExecutor &]" at line 32 of /workspace/bug/bug.cu

``` 

**To Reproduce**

Compile this reproducer with the `#if` enabled.

```
#include <matx.h>

int main()
{
  matx::cudaExecutor exec;

  auto t_x = matx::make_tensor<float>({16});
  (t_x = matx::linspace<float>(-15, 0, 16)).run(exec);

  auto t_max = matx::make_tensor<float>({1});
  auto t_max_idx = matx::make_tensor<matx::index_t>({1});

  (matx::mtie(t_max, t_max_idx) = matx::argmax(t_x)).run(exec);
  exec.sync();

  printf("argmax(t_x): max: %f, max_idx: %lld\n", t_max(0), t_max_idx(0));

  auto lz_fcn_x = matx::abs(t_x);
  //auto lz_fcn_x = t_x+1;

  auto t_fcn_x = matx::make_tensor<float>({16});
  (t_fcn_x = lz_fcn_x).run();
  (matx::mtie(t_max, t_max_idx) = matx::argmax(t_fcn_x)).run(exec);
  exec.sync();
  printf("argmax(t_fcn_x): max: %f, max_idx: %lld\n", t_max(0), t_max_idx(0));

  (t_max = matx::max(lz_fcn_x)).run(exec);
  exec.sync();
  printf("max(lz_fcn_x): %f\n", t_max(0));

#if 1
  (matx::mtie(t_max, t_max_idx) = matx::argmax(lz_fcn_x)).run(exec);
  exec.sync();
  printf("argmax(lz_fcn_x): max: %f, max_idx: %lld\n", t_max(0), t_max_idx(0));
#endif

  return 0;
}
```

**Expected Behavior**

Desired behavior is no compiler error and output:
```
argmax(t_x): max: 0.000000, max_idx: 15
argmax(t_fcn_x): max: 15.000000, max_idx: 0
max(lz_fcn_x): 15.000000
argmax(lz_fcn_x): max: 15.000000, max_idx: 0
```

**System Details (please complete the following information):**

 - OS: Ubuntu 22.04
 - CUDA version: 12.6
 - g++ version: 11.4

**Additional Context**

As shown in the reproducer, `max()` doesn't have this issue.  Also, storing the lazily-evaluated operator values to a memory backed tensor and then using `argmax()` on the tensor works.

### PR DESCRIPTION
**Pull request by tmartin-gh**
This fixes #946 by performing a copy of the operator to a temporary tensor.

### CODE REVIEW

File: include/matx/transforms/cub.h [hunk 1]
```diff
@@ -1227,43 +1227,62 @@ class matxCubSingleArgPlan_t {
...
-        temp_storage_bytes,
-        zipped_input,
-        zipped_output,
-        N,
-        cparams_.reduce_op,
-        cparams_.init,
-        stream);
+    else
+    {
+      // For a non-tensor input, such as matxBinaryOp, we need to make a temporary tensor
```
Comment (cliffburdick) [inline include/matx/transforms/cub.h:1278]: This should usually be done outside of the exec function and inside the impl function if possible using the "Supported" function. Here's how FFT and GEMM do it:

https://github.com/NVIDIA/MatX/blob/main/include/matx/transforms/fft/fft_cuda.h#L701-L702
https://github.com/NVIDIA/MatX/blob/main/include/matx/transforms/matmul/matmul_cuda.h#L1197-L1199

Is that possible here to make it clear what's supported?

**Review by cliffburdick — APPROVED** [review]
